/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ThemeNames } from "./components/json-editor/types";
export { ThemeNames } from "./components/json-editor/types";
export namespace Components {
    interface EditorPanel {
    }
    interface JsonEditor {
        "foldAll": () => Promise<void>;
        "readonly": boolean;
        /**
          * Theme of the editor
         */
        "theme"?: ThemeNames;
        "unfoldAll": () => Promise<void>;
        /**
          * Value that will be displayed inside the editor
         */
        "value": string;
    }
}
declare global {
    interface HTMLEditorPanelElement extends Components.EditorPanel, HTMLStencilElement {
    }
    var HTMLEditorPanelElement: {
        prototype: HTMLEditorPanelElement;
        new (): HTMLEditorPanelElement;
    };
    interface HTMLJsonEditorElement extends Components.JsonEditor, HTMLStencilElement {
    }
    var HTMLJsonEditorElement: {
        prototype: HTMLJsonEditorElement;
        new (): HTMLJsonEditorElement;
    };
    interface HTMLElementTagNameMap {
        "editor-panel": HTMLEditorPanelElement;
        "json-editor": HTMLJsonEditorElement;
    }
}
declare namespace LocalJSX {
    interface EditorPanel {
    }
    interface JsonEditor {
        "readonly"?: boolean;
        /**
          * Theme of the editor
         */
        "theme"?: ThemeNames;
        /**
          * Value that will be displayed inside the editor
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "editor-panel": EditorPanel;
        "json-editor": JsonEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "editor-panel": LocalJSX.EditorPanel & JSXBase.HTMLAttributes<HTMLEditorPanelElement>;
            "json-editor": LocalJSX.JsonEditor & JSXBase.HTMLAttributes<HTMLJsonEditorElement>;
        }
    }
}
